site_name: Hotmaps Wiki
site_url: https://danieldreke.github.io/serverless-wiki/
repo_url: https://github.com/danieldreke/serverless-wiki/wiki
edit_uri: ./_edit
hooks:
  - fix_edit_url.py
plugins:
  - search
theme:
  name: material
  # language: en
  # locale: en
  features:
    - content.action.edit
