# site_name: Wiki Name
site_url: https://danieldreke.github.io/serverless-wiki/
repo_url: https://github.com/danieldreke/serverless-wiki/wiki
edit_uri: ./_edit
hooks:
  - change_edit_url.py
plugins:
  - search
theme:
  name: material
  features:
    - content.action.edit
